### PR TITLE
Hristova/tpg pattgen tools

### LINKED ISSUE #14: To add pattern generation/validation app and scripts
I am working now on finishing these tools and they will be available via a new PR to tpgtools.

### LINKED ISSUE #15: Channel map usage from the frame-based "workload" app
At the moment the assignment of channel numbers during the hit extraction seems to be broken in the `wibeth_tpg_workload_emulator` app. All channels numbers in the NAIVE and AVX implementation are 0. This needs closer look and a fix in order to use this app for the algorithm validation.

### LINKED ISSUE #20: Implement the functionality to output multiple frames of ADC data within the wibeth_tpg_algorithms_emulator app
Currently, wibeth_tpg_algorithms_emulator app can only output ADC data for a single frame.  Given the option to output TP data for a specified number of TRs it would be useful to have the corresponding ADC data for those TRs, for validation purposes.

### PR DESCRIPTION
**Pull request by hristovaivana**
In this PR the following changes were made

Add app for pattern generation (to provide well known input for NAIVE vs AVX testing)
Fix was needed to make use of offline channel in the validation. 

This PR is related to the following issues 
https://github.com/DUNE-DAQ/tpgtools/issues/14
https://github.com/DUNE-DAQ/tpgtools/issues/15
https://github.com/DUNE-DAQ/tpgtools/issues/20

The next step following from this PR will be to add Python (and pytest-based) for TPG regression testing.

### CODE REVIEW

**Comment by hristovaivana** [comment]
The review comments were incorporated and the feature discussed in https://github.com/DUNE-DAQ/tpgtools/issues/20 is included.

**Comment by adam-abed-abud** [comment]
Hi Ivana, thanks for preparing the PR. Here are my comments: 

-- I see that the number of applications in TPGtools is increasing. I believe it will be harder to maintein the repository in the future. Why don't you merge the functionality of the newly created `wibeth_tpg_pattern_generator` with the `wibeth_tpg_workload_emulator` and add a bool option for enabling pattern_generation? 

-- I like that you added a new method in the emulator core class (`set_num_frames_to_save`) which would work for a frame based emulator (`wibeth_tpg_workload_emulator`) as well as a Trigger Record emulator (`wibeth_tpg_algorithms_emulator`). I don't agree with adding the method `void register_TR_info` as it may not be needed for example in `wibeth_tpg_workload_emulator`


-- I would also propose to make the function `save_raw_data` that is currently available in `TPGUtils.hpp` as a memthod of the `tpg_emulator_avx` and `tpg_emulator_naive` classes. In this way you can write to file directly the offline channel number as well as avod passing extra parameters to the function.

**Comment by hristovaivana** [comment]
Hi Adam, 
thank you very much for the good comments, they are very helpful! 
In the current state, this branch contains the proposed changes in your 2nd and 3rd paragraphs. 
I've created and issue https://github.com/DUNE-DAQ/tpgtools/issues/25 for the first comment and I will be working on it now, but it is not included at the moment.

**Review by adam-abed-abud — APPROVED** [review]
Thanks for preparing the PR. I tested both the pattern generation step as well as the TPG workload emulator.

**Pull request merged**
